theme:
  name: material
  language: it

  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - toc.integrate


markdown_extensions:
  - meta
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences

site_name: Dungeon World

repo_url: https://github.com/mazzaf01/Italian-Dungeon-World

nav:
  - Regole:
    - Come giocare: gioco/come_giocare.md
    - Danni e morte: gioco/danni.md
    - Magia: gioco/magia.md
    - Gregari: gioco/gregari.md
    - La Vita da Avventuriero: gioco/vita_da_avventuriero.md
    - Equipaggiamento: gioco/equipaggiamento.md
    - Oggetti magici: gioco/oggetti_magici.md
  - Game Master:
    - Introduzione al Ruolo: gm/intro.md
    - Mosse del GM: gm/mosse_gm.md
    - Mosse del Dungeon: gm/mosse_dungeon.md
    - Affronare la Prima Sessione: gm/prima_sessione.md
    - Gestire i Fronti: gm/fronti.md
    - Il Mondo: gm/mondo.md
  - Personaggi:
    - Creazione del Personaggio: pgs/creazione.md
    - Allineamento: pgs/allineamento.md
    - Evoluzione: pgs/evoluzione.md
    - Legami: pgs/legami.md
    - Mosse: pgs/mosse_pg.md
  - Classi:
    - Lista: classi/lista.md
    - Barbaro: classi/barbaro.md
    - Bardo: classi/bardo.md
    - Chierico: classi/chierico.md
    - Guerriero: classi/guerriero.md
  - Mostri:
    - Panoramica: mostri/panoramica.md