theme:
  name: material
  language: it

  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - toc.integrate


markdown_extensions:
  - meta
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences

site_name: Dungeon World

repo_url: https://github.com/mazzaf01/Italian-Dungeon-World
edit_uri: ""

nav:
  - Benvenuto:
    - Dungeon World: index.md
  - Regole:
    - Come giocare: regole/come_giocare.md
    - Danni e morte: regole/danni.md
    - Magia: regole/magia.md
    - Gregari: regole/gregari.md
    - La Vita da Avventuriero: regole/vita_da_avventuriero.md
    - Equipaggiamento: regole/equipaggiamento.md
    - Oggetti magici: regole/oggetti_magici.md
  - Game Master:
    - Introduzione al Ruolo: gm/intro.md
    - Mosse del GM: gm/mosse_gm.md
    - Mosse del Dungeon: gm/mosse_dungeon.md
    - Affronare la Prima Sessione: gm/prima_sessione.md
    - Gestire i Fronti: gm/fronti.md
    - Il Mondo: gm/mondo.md
  - Giocatori:
    - Creazione del Personaggio: pgs/creazione.md
    - Allineamento: pgs/allineamento.md
    - Evoluzione: pgs/evoluzione.md
    - Legami: pgs/legami.md
    - Lista delle mosse: pgs/mosse_pg.md
  - Classi:
    - Panoramica delle Classi: classi/panoramica.md
    - Barbaro: classi/barbaro.md
    - Bardo: classi/bardo.md
    - Chierico: classi/chierico.md
    - Incantesimi del Chierico: classi/incantesimi/chierico.md
    - Druido: classi/druido.md
    - Guerriero: classi/guerriero.md
    - Ladro: classi/ladro.md
    - Mago: classi/mago.md
    - Incantesimi del Mago: classi/incantesimi/mago.md
    - Paladino: classi/paladino.md
    - Ramingo: classi/ramingo.md
  - Mostri:
    - Panoramica: mostri/panoramica.md